name: Java CI with Maven and Docker Compose

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      # Add a step to set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Create secret.properties in src/main/resources directory
        run: |
            echo "secret.JwtSecret = ${{ secrets.JWT_SECRET }}" > src/main/resources/secret.properties
            echo "spring.datasource.url=jdbc:mariadb://${{ secrets.DB_URL }}:3306/TaskPro" >> src/main/resources/secret.properties
            echo "spring.datasource.username=admin" >> src/main/resources/secret.properties
            echo "spring.datasource.password=${{ secrets.DB_PASSWORD }" >> src/main/resources/secret.properties

      # Add a step to build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
