name: Java CI with Maven and Docker Compose

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Add a step to set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Add a step to start the MariaDB service using Docker Compose
      - name: Start MariaDB
        run: docker-compose up -d

      # Add a step to set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Add a step to build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Add a step to run tests
      - name: Run Tests
        run: |
          mvn test || exit 1

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      # Add a step to stop the MariaDB service using Docker Compose
      - name: Stop MariaDB
        run: docker-compose down
